version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maxi-api
    restart: always
    environment:
      - PORT=${PORT}
      - SERVER_URL=${SERVER_URL}
      - API_VERSION=${API_VERSION}
      - MONGODB=${MONGODB_DOCKER_SERVICE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - PAGINATION_DEFAULT_PAGE=${PAGINATION_DEFAULT_PAGE}
      - PAGINATION_DEFAULT_LIMIT=${PAGINATION_DEFAULT_LIMIT}
      - PAGINATION_DEFAULT_ORDER=${PAGINATION_DEFAULT_ORDER}
      - FILE_VALID_EXTENSIONS=${FILE_VALID_EXTENSIONS}
      - FILE_MAX_SIZE=${FILE_MAX_SIZE}
      - FILE_UPLOAD_PLATFORM=${FILE_UPLOAD_PLATFORM}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_FROM=${MAIL_FROM}
      - SMS_ACCOUNT_SID=${SMS_ACCOUNT_SID}
      - SMS_AUTH_TOKEN=${SMS_AUTH_TOKEN}
      - SMS_MESSAGING_SERVICE_SID=${SMS_MESSAGING_SERVICE_SID}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo_service

  mongo_service:
    image: mongo:latest
    container_name: mongo_service
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata: 